version: '3.9'

services:
  db:
    image: postgres:15.5-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_name
